### ISSUE TITLE
lambda step function 과정 중 optimize 람다 코드 분리 및 작성

### ISSUE THREAD

**Issue by subeans** [ddps-lab/lambda-optimize-serving#5]

**Comment by subeans** [comment]
lambda-optimize 함수 분리
1. ONNX convert 함수 분리 - 완료 
2. TVM convert 함수 분리 - 진행 중 ( intel / arm ) 
이미지 생성하는 과정에서
```
-- VTA build with VTA_HW_PATH=/var/task/lambda-optimize-serving/lambda-optimize/intel_tvm/tvm/3rdparty/vta-hw
Traceback (most recent call last):
  File "/var/task/lambda-optimize-serving/lambda-optimize/intel_tvm/tvm/3rdparty/vta-hw/config/vta_config.py", line 308, in <module>
    main()
  File "/var/task/lambda-optimize-serving/lambda-optimize/intel_tvm/tvm/3rdparty/vta-hw/config/vta_config.py", line 196, in main
    raise RuntimeError("Cannot find config in %s" % str(path_list))
RuntimeError: Cannot find config in ['vta_config.json', '/var/task/lambda-optimize-serving/lambda-optimize/intel_tvm/tvm/3rdparty/vta-hw/config/vta_config.json']
-- Build VTA runtime with target: 
Traceback (most recent call last):
  File "/var/task/lambda-optimize-serving/lambda-optimize/intel_tvm/tvm/3rdparty/vta-hw/config/vta_config.py", line 308, in <module>
    main()
  File "/var/task/lambda-optimize-serving/lambda-optimize/intel_tvm/tvm/3rdparty/vta-hw/config/vta_config.py", line 196, in main
    raise RuntimeError("Cannot find config in %s" % str(path_list))
RuntimeError: Cannot find config in ['vta_config.json', '/var/task/lambda-optimize-serving/lambda-optimize/intel_tvm/tvm/3rdparty/vta-hw/config/vta_config.json']
CMake Error at cmake/utils/FindLLVM.cmake:47 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/modules/LLVM.cmake:31 (find_llvm)
  CMakeLists.txt:427 (include)
```
에러 발생으로 해결 중에 있습니다.
